#!/usr/bin/env bash
set -euo pipefail

# Publish Forge agent + coordinator skill + mode skills.
#
# Publishes to:
#   ~/.copilot/agents/Forge.agent.md
#   ~/.copilot/skills/forge/SKILL.md
#   ~/.copilot/skills/forge-{mode}/SKILL.md (6 modes)
#
# Usage:
#   ./publish.sh                # publish everything
#   ./publish.sh --dry-run      # preview without writing

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

AGENTS_TARGET="$HOME/.copilot/agents"
SKILLS_TARGET="$HOME/.copilot/skills"

echo "🔨 Forge Publisher"
echo "   Source: $SCRIPT_DIR"
echo ""

SUCCESS=0
TOTAL=0

# --- Helper ---
publish_file() {
  local src="$1" dst="$2" label="$3"
  TOTAL=$((TOTAL + 1))
  if [ ! -f "$src" ]; then
    echo "   ❌ Missing: $src"
    return 1
  fi
  local chars
  chars=$(wc -c < "$src" | tr -d ' ')
  if $DRY_RUN; then
    echo "   Would write: $dst ($chars chars)"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "   ✅ $label ($chars chars)"
  fi
  SUCCESS=$((SUCCESS + 1))
}

# --- Step 1: Agent file ---
echo "🤖 Publishing agent..."

# Build agent with frontmatter
AGENT_SRC="$SCRIPT_DIR/forge.agent.md"
AGENT_DST="$AGENTS_TARGET/Forge.agent.md"
TOTAL=$((TOTAL + 1))

if [ ! -f "$AGENT_SRC" ]; then
  echo "   ❌ Missing: $AGENT_SRC"
else
  # Extract body — skip the H1 title and its description, keep EVERYTHING else
  # This includes: CRITICAL First Action, Pressure Table, Dispatch Examples, etc.
  # We skip lines 1-4 (# Forge, blank, description, blank) and keep from line 5 onwards
  BODY=$(awk 'NR>1 && /^[#*>\[]/{found=1} found{print}' "$AGENT_SRC")
  if [ -z "$BODY" ]; then
    BODY=$(tail -n +3 "$AGENT_SRC")
  fi

  FRONTMATTER="---
description: 'Your dev partner. Understands tasks, routes to the right mode, coordinates specialists, never loses the thread.'
model: claude-opus-4.6
tools: [\"*\"]
---"

  RENDERED="${FRONTMATTER}

<!-- AUTO-GENERATED by publish.sh from forge.agent.md. DO NOT EDIT. -->

${BODY}
"

  RENDERED_CHARS=${#RENDERED}
  if $DRY_RUN; then
    echo "   Would write: $AGENT_DST ($RENDERED_CHARS chars)"
  else
    mkdir -p "$AGENTS_TARGET"
    printf '%s' "$RENDERED" > "$AGENT_DST"
    echo "   ✅ Forge.agent.md ($RENDERED_CHARS chars)"
  fi
  SUCCESS=$((SUCCESS + 1))
fi

# --- Step 2: Coordinator skill ---
echo ""
echo "📜 Publishing coordinator skill..."
publish_file "$SCRIPT_DIR/SKILL.md" "$SKILLS_TARGET/forge/SKILL.md" "forge/SKILL.md"

# --- Step 3: Mode skills ---
echo ""
echo "⚙️  Publishing mode skills..."

MODES=("explore" "ideate" "plan" "execute" "verify" "memory" "product")

for mode in "${MODES[@]}"; do
  publish_file \
    "$SCRIPT_DIR/modes/${mode}.md" \
    "$SKILLS_TARGET/forge-${mode}/SKILL.md" \
    "forge-${mode}/SKILL.md"
done

# --- Step 4: Product-hub library ---
echo ""
echo "📦 Publishing product-hub library..."

PRODUCT_HUB="$SCRIPT_DIR/product-hub"

if [ -f "$PRODUCT_HUB/scripts/index.js" ]; then
  publish_file \
    "$PRODUCT_HUB/scripts/index.js" \
    "$SKILLS_TARGET/forge-product/scripts/index.js" \
    "forge-product/scripts/index.js"
else
  echo "   ⚠️  Product-hub not built. Run: cd product-hub && npm run build"
fi

if [ -f "$PRODUCT_HUB/references/storage.md" ]; then
  publish_file \
    "$PRODUCT_HUB/references/storage.md" \
    "$SKILLS_TARGET/forge-product/references/storage.md" \
    "forge-product/references/storage.md"
fi

# --- Summary ---
echo ""
echo "═══════════════════════════════════════════════"
if $DRY_RUN; then
  echo "📊 Dry-run: would publish $SUCCESS/$TOTAL files"
else
  echo "✅ Published $SUCCESS/$TOTAL files"
  echo "   Agent:     $AGENTS_TARGET/Forge.agent.md"
  echo "   Skills:    $SKILLS_TARGET/forge*/SKILL.md"
fi
echo ""
echo "Files:"
echo "   Agent:       ~/.copilot/agents/Forge.agent.md"
echo "   Coordinator: ~/.copilot/skills/forge/SKILL.md"
for mode in "${MODES[@]}"; do
  echo "   Mode:        ~/.copilot/skills/forge-${mode}/SKILL.md"
done

[ "$SUCCESS" -eq "$TOTAL" ] || exit 1
