# Build the 3-plugin Forge system (PowerShell):
#   1. forge-shared — shared skills (infra, architecture, PM, shared modes, sole MCP owner)
#   2. forge        — Opus coordinator (agent + 3 unique skills)
#   3. forge-gpt    — GPT coordinator (agent + 3 unique skills)
#
# Usage:
#   .\build-all.ps1              # build all 3
#   .\build-all.ps1 -Install     # build + install all 3
#   .\build-all.ps1 -DryRun      # preview

param(
    [switch]$DryRun,
    [switch]$Install
)

$ErrorActionPreference = 'Stop'

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Definition
$DistShared = Join-Path $ScriptDir 'dist-shared'
$DistForge  = Join-Path $ScriptDir 'dist'
$DistGpt    = Join-Path $ScriptDir 'dist-forge-gpt'

$script:Success = 0
$script:Total   = 0

# ── Helpers ──────────────────────────────────────

function Copy-PluginFile {
    param([string]$Src, [string]$Dst, [string]$Label)
    $script:Total++
    if (-not (Test-Path $Src -PathType Leaf)) {
        Write-Host "   ❌ Missing: $Src"
        return $false
    }
    if ($DryRun) {
        Write-Host "   Would copy: $Label"
    } else {
        $parent = Split-Path -Parent $Dst
        if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
        Copy-Item -Path $Src -Destination $Dst -Force
        Write-Host "   ✅ $Label"
    }
    $script:Success++
    return $true
}

function Copy-PluginDir {
    param([string]$Src, [string]$Dst, [string]$Label)
    $script:Total++
    if (-not (Test-Path $Src -PathType Container)) {
        Write-Host "   ❌ Missing dir: $Src"
        return $false
    }
    if ($DryRun) {
        Write-Host "   Would copy dir: $Label"
    } else {
        if (-not (Test-Path $Dst)) { New-Item -ItemType Directory -Path $Dst -Force | Out-Null }
        Copy-Item -Path "$Src\*" -Destination $Dst -Recurse -Force
        Write-Host "   ✅ $Label"
    }
    $script:Success++
    return $true
}

function Write-AgentBundle {
    param(
        [string]$Src, [string]$Dst,
        [string]$Description, [string]$Model,
        [string]$SourceLabel, [string]$OutputLabel
    )
    $script:Total++
    if (-not (Test-Path $Src -PathType Leaf)) {
        Write-Host "   ❌ Missing: $Src"
        return $false
    }
    $allLines = (Get-Content $Src -Raw) -split "`n"
    $found = $false; $bodyLines = @()
    for ($i = 1; $i -lt $allLines.Count; $i++) {
        if (-not $found -and $allLines[$i] -match '^[#*>\[]') { $found = $true }
        if ($found) { $bodyLines += $allLines[$i] }
    }
    $body = if ($bodyLines.Count -gt 0) { $bodyLines -join "`n" } else { ($allLines | Select-Object -Skip 2) -join "`n" }

    $rendered = @"
---
description: '$Description'
model: $Model
tools: ["*"]
---

<!-- AUTO-GENERATED by build-all.ps1 from $SourceLabel. DO NOT EDIT. -->

$body
"@

    if ($DryRun) {
        Write-Host "   Would write: $OutputLabel ($($rendered.Length) chars)"
    } else {
        $parent = Split-Path -Parent $Dst
        if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
        [System.IO.File]::WriteAllText($Dst, $rendered)
        Write-Host "   ✅ $OutputLabel ($($rendered.Length) chars)"
    }
    $script:Success++
    return $true
}

function Write-ReframedManifest {
    param(
        [string]$Src,
        [string]$Dst,
        [string]$Name,
        [string]$Desc,
        [string[]]$ExtraKeywords,
        [switch]$StripMcpServers
    )
    $script:Total++
    if (-not (Test-Path $Src -PathType Leaf)) {
        Write-Host "   ❌ Missing: $Src"
        return $false
    }
    $base = Get-Content $Src -Raw | ConvertFrom-Json
    $manifest = [ordered]@{}
    foreach ($prop in $base.PSObject.Properties) { $manifest[$prop.Name] = $prop.Value }
    $manifest.name = $Name
    $manifest.description = $Desc
    $manifest.keywords = @((@($ExtraKeywords) + @($base.keywords)) | Select-Object -Unique)
    if ($StripMcpServers) { $manifest.Remove('mcpServers') }

    $rendered = ($manifest | ConvertTo-Json -Depth 10) + "`n"
    if ($DryRun) {
        Write-Host "   Would write: plugin.json ($Name)"
    } else {
        $parent = Split-Path -Parent $Dst
        if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
        [System.IO.File]::WriteAllText($Dst, $rendered)
        Write-Host "   ✅ plugin.json ($Name)"
    }
    $script:Success++
    return $true
}

# ═══════════════════════════════════════════════
# PLUGIN 1: forge-shared
# ═══════════════════════════════════════════════
Write-Host "╔═══════════════════════════════════════════════╗"
Write-Host "║  1/3  forge-shared                            ║"
Write-Host "╚═══════════════════════════════════════════════╝"

if (-not $DryRun) {
    if (Test-Path $DistShared) { Remove-Item -Recurse -Force $DistShared }
    New-Item -ItemType Directory -Path $DistShared -Force | Out-Null
}

Write-Host "📦 Manifest..."
Copy-PluginFile "$ScriptDir\plugin-shared.json" "$DistShared\plugin.json" "plugin.json" | Out-Null
Copy-PluginFile "$ScriptDir\.mcp.json" "$DistShared\.mcp.json" ".mcp.json" | Out-Null

Write-Host "⚙️  Shared forge modes..."
foreach ($mode in @('explore','ideate','design','plan','memory','product','assess')) {
    Copy-PluginFile "$ScriptDir\agents\forge\modes\$mode.md" "$DistShared\skills\forge-$mode\SKILL.md" "skills/forge-$mode/SKILL.md" | Out-Null
}

Write-Host "📦 Product-hub..."
$phScript = "$ScriptDir\agents\forge\product-hub\scripts\index.js"
if (Test-Path $phScript -PathType Leaf) {
    Copy-PluginFile $phScript "$DistShared\skills\forge-product\scripts\index.js" "skills/forge-product/scripts/index.js" | Out-Null
}
$phRefs = "$ScriptDir\agents\forge\product-hub\references"
if (Test-Path $phRefs -PathType Container) {
    Copy-PluginDir $phRefs "$DistShared\skills\forge-product\references" "skills/forge-product/references/" | Out-Null
}

Write-Host "📋 Shared preferences..."
$sharedDir = "$ScriptDir\agents\forge\shared"
if (Test-Path $sharedDir -PathType Container) {
    Get-ChildItem "$sharedDir\*.md" | ForEach-Object {
        Copy-PluginFile $_.FullName "$DistShared\skills\forge-shared-prefs\references\$($_.Name)" "skills/forge-shared-prefs/references/$($_.Name)" | Out-Null
    }
}

Write-Host "📚 Forge references..."
$refsDir = "$ScriptDir\agents\forge\references"
if (Test-Path $refsDir -PathType Container) {
    Get-ChildItem "$refsDir\*.md" | ForEach-Object {
        Copy-PluginFile $_.FullName "$DistShared\skills\forge-shared-prefs\references\$($_.Name)" "skills/forge-shared-prefs/references/$($_.Name)" | Out-Null
    }
}

Write-Host "🧾 Forge schemas..."
$schemasDir = "$ScriptDir\agents\forge\schemas"
if (Test-Path $schemasDir -PathType Container) {
    Get-ChildItem "$schemasDir\*.md" | ForEach-Object {
        Copy-PluginFile $_.FullName "$DistShared\skills\forge-shared-prefs\references\schemas\$($_.Name)" "skills/forge-shared-prefs/references/schemas/$($_.Name)" | Out-Null
    }
}

Write-Host "📐 Forge specs..."
foreach ($spec in @('visual-vocabulary.md','external-voice.md','design-artifacts.md')) {
    $specPath = "$ScriptDir\agents\forge\docs\specs\$spec"
    if (Test-Path $specPath) {
        Copy-PluginFile $specPath "$DistShared\skills\forge-shared-prefs\references\specs\$spec" "skills/forge-shared-prefs/references/specs/$spec" | Out-Null
    }
}

Write-Host "📄 Design review template..."
$tmplPath = "$ScriptDir\agents\forge\templates\design-review.html"
if (Test-Path $tmplPath) {
    Copy-PluginFile $tmplPath "$DistShared\skills\forge-shared-prefs\references\templates\design-review.html" "skills/forge-shared-prefs/references/templates/design-review.html" | Out-Null
}

Write-Host "🔧 Infrastructure skills..."
foreach ($skill in @('experts-council','backlog','agents-hub','copilot-cli-skill')) {
    $srcDir = "$ScriptDir\skills\$skill"
    $dstDir = "$DistShared\skills\$skill"
    if (-not (Test-Path $srcDir -PathType Container)) {
        Write-Host "   ❌ Missing: skills/$skill/"
        $script:Total++
        continue
    }
    Copy-PluginFile "$srcDir\SKILL.md" "$dstDir\SKILL.md" "skills/$skill/SKILL.md" | Out-Null
    $si = "$srcDir\scripts\index.js"
    if (Test-Path $si -PathType Leaf) { Copy-PluginFile $si "$dstDir\scripts\index.js" "skills/$skill/scripts/index.js" | Out-Null }
    $sr = "$srcDir\references"
    if (Test-Path $sr -PathType Container) { Copy-PluginDir $sr "$dstDir\references" "skills/$skill/references/" | Out-Null }
}

Write-Host "🏗️  Architecture skills..."
foreach ($skill in @('backend-architecture','frontend-architecture')) {
    $srcDir = "$ScriptDir\skills\$skill"
    $dstDir = "$DistShared\skills\$skill"
    if (-not (Test-Path $srcDir -PathType Container)) {
        Write-Host "   ❌ Missing: skills/$skill/"
        $script:Total++
        continue
    }
    Copy-PluginFile "$srcDir\SKILL.md" "$dstDir\SKILL.md" "skills/$skill/SKILL.md" | Out-Null
    $sr = "$srcDir\references"
    if (Test-Path $sr -PathType Container) { Copy-PluginDir $sr "$dstDir\references" "skills/$skill/references/" | Out-Null }
}

Write-Host "📋 PM skills..."
foreach ($skill in @('jobs-to-be-done','made-to-stick','copywriting','lean-startup','storybrand-messaging','cro-methodology','page-cro')) {
    $srcDir = "$ScriptDir\skills\$skill"
    $dstDir = "$DistShared\skills\$skill"
    if (-not (Test-Path $srcDir -PathType Container)) {
        Write-Host "   ⚠️  Optional: skills/$skill/ (skipping)"
        continue
    }
    Copy-PluginFile "$srcDir\SKILL.md" "$dstDir\SKILL.md" "skills/$skill/SKILL.md" | Out-Null
    $sr = "$srcDir\references"
    if (Test-Path $sr -PathType Container) { Copy-PluginDir $sr "$dstDir\references" "skills/$skill/references/" | Out-Null }
}

# ═══════════════════════════════════════════════
# PLUGIN 2: forge (Opus — 3 unique skills + agent)
# ═══════════════════════════════════════════════
Write-Host ""
Write-Host "╔═══════════════════════════════════════════════╗"
Write-Host "║  2/3  forge (Opus)                            ║"
Write-Host "╚═══════════════════════════════════════════════╝"

if (-not $DryRun) {
    if (Test-Path $DistForge) { Remove-Item -Recurse -Force $DistForge }
    New-Item -ItemType Directory -Path $DistForge -Force | Out-Null
}

Write-Host "📦 Manifest..."
Write-ReframedManifest `
    "$ScriptDir\plugin.json" `
    "$DistForge\plugin.json" `
    "forge" `
    "Forge dev partner — dispatch coordinator with specialized skills for product management, architecture guidance, backlog tracking, expert council reviews, and parallel worker execution." `
    @() `
    -StripMcpServers | Out-Null

Write-Host "🤖 Agent..."
Write-AgentBundle `
    "$ScriptDir\agents\forge\forge.agent.md" `
    "$DistForge\agents\Forge.agent.md" `
    "Your dev partner. Understands tasks, routes to the right mode, coordinates specialists, never loses the thread." `
    "claude-opus-4.6" `
    "forge.agent.md" `
    "agents/Forge.agent.md" | Out-Null

Write-Host "📜 Coordinator skill..."
Copy-PluginFile "$ScriptDir\agents\forge\SKILL.md" "$DistForge\skills\forge\SKILL.md" "skills/forge/SKILL.md" | Out-Null

Write-Host "⚙️  Opus modes..."
Copy-PluginFile "$ScriptDir\agents\forge\modes\execute.md" "$DistForge\skills\forge-execute\SKILL.md" "skills/forge-execute/SKILL.md" | Out-Null
Copy-PluginFile "$ScriptDir\agents\forge\modes\verify.md" "$DistForge\skills\forge-verify\SKILL.md" "skills/forge-verify/SKILL.md" | Out-Null

# ═══════════════════════════════════════════════
# PLUGIN 3: forge-gpt (3 unique skills + agent)
# ═══════════════════════════════════════════════
Write-Host ""
Write-Host "╔═══════════════════════════════════════════════╗"
Write-Host "║  3/3  forge-gpt                               ║"
Write-Host "╚═══════════════════════════════════════════════╝"

if (-not $DryRun) {
    if (Test-Path $DistGpt) { Remove-Item -Recurse -Force $DistGpt }
    New-Item -ItemType Directory -Path $DistGpt -Force | Out-Null
}

Write-Host "📦 Manifest..."
Write-ReframedManifest `
    "$ScriptDir\plugin.json" `
    "$DistGpt\plugin.json" `
    "forge-gpt" `
    "Forge-GPT coordinator — GPT-optimized dispatch with contract-driven execution and verification." `
    @('forge-gpt','gpt-family','contract-driven') `
    -StripMcpServers | Out-Null

Write-Host "🤖 Agent..."
Write-AgentBundle `
    "$ScriptDir\agents\forge-gpt\forge-gpt.agent.md" `
    "$DistGpt\agents\Forge-GPT.agent.md" `
    "Contract-driven GPT coordinator. Routes work, constructs Mission Briefs, validates REPORTs, and stops." `
    "gpt-5.4" `
    "forge-gpt.agent.md" `
    "agents/Forge-GPT.agent.md" | Out-Null

Write-Host "📜 GPT coordinator skill..."
Copy-PluginFile "$ScriptDir\agents\forge-gpt\SKILL.md" "$DistGpt\skills\forge-gpt\SKILL.md" "skills/forge-gpt/SKILL.md" | Out-Null

Write-Host "⚙️  GPT modes..."
foreach ($mode in @('execute','verify','explore','ideate','design','plan','memory','product','assess')) {
    Copy-PluginFile "$ScriptDir\agents\forge-gpt\modes\$mode.md" "$DistGpt\skills\forge-$mode-gpt\SKILL.md" "skills/forge-$mode-gpt/SKILL.md" | Out-Null
}

# ═══════════════════════════════════════════════
# Cleanup
# ═══════════════════════════════════════════════
if (-not $DryRun) {
    foreach ($d in @($DistShared, $DistForge, $DistGpt)) {
        Get-ChildItem -Path $d -Recurse -Filter '.DS_Store' -ErrorAction SilentlyContinue |
            Remove-Item -Force -ErrorAction SilentlyContinue
    }
}

# ═══════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════
Write-Host ""
Write-Host "═══════════════════════════════════════════════"
if ($DryRun) {
    Write-Host "📊 Dry-run: would build $($script:Success)/$($script:Total) components"
} else {
    $s1 = (Get-ChildItem -Path $DistShared -Recurse -File).Count
    $s2 = (Get-ChildItem -Path $DistForge -Recurse -File).Count
    $s3 = (Get-ChildItem -Path $DistGpt -Recurse -File).Count
    $sz1 = "{0:N1} MB" -f ((Get-ChildItem -Path $DistShared -Recurse -File | Measure-Object -Property Length -Sum).Sum / 1MB)
    $sz2 = "{0:N0} KB" -f ((Get-ChildItem -Path $DistForge -Recurse -File | Measure-Object -Property Length -Sum).Sum / 1KB)
    $sz3 = "{0:N0} KB" -f ((Get-ChildItem -Path $DistGpt -Recurse -File | Measure-Object -Property Length -Sum).Sum / 1KB)
    Write-Host "✅ Built $($script:Success)/$($script:Total) components"
    Write-Host ""
    Write-Host "  forge-shared:  $s1 files  ($sz1)"
    Write-Host "  forge:         $s2 files  ($sz2)"
    Write-Host "  forge-gpt:     $s3 files  ($sz3)"
}

# ═══════════════════════════════════════════════
# Install
# ═══════════════════════════════════════════════
if ($Install -and -not $DryRun) {
    Write-Host ""
    Write-Host "🚀 Installing plugins..."

    try { copilot plugin uninstall forge-shared 2>$null } catch {}
    try { copilot plugin uninstall forge 2>$null } catch {}
    try { copilot plugin uninstall forge-gpt 2>$null } catch {}

    copilot plugin install $DistShared
    copilot plugin install $DistForge
    copilot plugin install $DistGpt

    Write-Host ""
    copilot plugin list
}

Write-Host ""
Write-Host "═══════════════════════════════════════════════"
if ($script:Success -ne $script:Total) { exit 1 }
