#!/usr/bin/env bash
set -euo pipefail

# Build the 3-plugin Forge system:
#   1. forge-shared — shared skills (infra, architecture, PM, shared modes)
#   2. forge        — Opus coordinator (agent + 3 unique skills)
#   3. forge-gpt    — GPT coordinator (agent + 3 unique skills)
#
# Usage:
#   ./build-all.sh              # build all 3
#   ./build-all.sh --install    # build + install all 3
#   ./build-all.sh --dry-run    # preview

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DIST_SHARED="$SCRIPT_DIR/dist-shared"
DIST_FORGE="$SCRIPT_DIR/dist"
DIST_GPT="$SCRIPT_DIR/dist-forge-gpt"
DRY_RUN=false
INSTALL=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --install) INSTALL=true ;;
    *) echo "Unknown: $arg"; exit 1 ;;
  esac
done

SUCCESS=0
TOTAL=0

copy_file() {
  local src="$1" dst="$2" label="$3"
  TOTAL=$((TOTAL + 1))
  if [ ! -f "$src" ]; then
    echo "   ❌ Missing: $src"
    return 1
  fi
  if $DRY_RUN; then
    echo "   Would copy: $label"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "   ✅ $label"
  fi
  SUCCESS=$((SUCCESS + 1))
}

copy_dir() {
  local src="$1" dst="$2" label="$3"
  TOTAL=$((TOTAL + 1))
  if [ ! -d "$src" ]; then
    echo "   ❌ Missing dir: $src"
    return 1
  fi
  if $DRY_RUN; then
    echo "   Would copy dir: $label"
  else
    mkdir -p "$dst"
    cp -r "$src"/* "$dst"/
    echo "   ✅ $label"
  fi
  SUCCESS=$((SUCCESS + 1))
}

write_agent() {
  local src="$1" dst="$2" description="$3" model="$4" src_label="$5" out_label="$6"
  TOTAL=$((TOTAL + 1))
  if [ ! -f "$src" ]; then
    echo "   ❌ Missing: $src"
    return 1
  fi
  BODY=$(awk 'NR>1 && /^[#*>\[]/{found=1} found{print}' "$src")
  if [ -z "$BODY" ]; then
    BODY=$(tail -n +3 "$src")
  fi
  RENDERED="---
description: '${description}'
model: ${model}
tools: [\"*\"]
---

<!-- AUTO-GENERATED by build-all.sh from ${src_label}. DO NOT EDIT. -->

${BODY}
"
  if $DRY_RUN; then
    echo "   Would write: $out_label (${#RENDERED} chars)"
  else
    mkdir -p "$(dirname "$dst")"
    printf '%s' "$RENDERED" > "$dst"
    echo "   ✅ $out_label (${#RENDERED} chars)"
  fi
  SUCCESS=$((SUCCESS + 1))
}

# ═══════════════════════════════════════════════
# PLUGIN 1: forge-shared
# ═══════════════════════════════════════════════
echo "╔═══════════════════════════════════════════════╗"
echo "║  1/3  forge-shared                            ║"
echo "╚═══════════════════════════════════════════════╝"

if ! $DRY_RUN; then rm -rf "$DIST_SHARED"; mkdir -p "$DIST_SHARED"; fi

# Manifest
echo "📦 Manifest..."
copy_file "$SCRIPT_DIR/plugin-shared.json" "$DIST_SHARED/plugin.json" "plugin.json"

# Shared forge modes
echo "⚙️  Shared forge modes..."
SHARED_MODES=("explore" "ideate" "design" "plan" "memory" "product")
for mode in "${SHARED_MODES[@]}"; do
  copy_file \
    "$SCRIPT_DIR/agents/forge/modes/${mode}.md" \
    "$DIST_SHARED/skills/forge-${mode}/SKILL.md" \
    "skills/forge-${mode}/SKILL.md"
done

# Product-hub
echo "📦 Product-hub..."
if [ -f "$SCRIPT_DIR/agents/forge/product-hub/scripts/index.js" ]; then
  copy_file "$SCRIPT_DIR/agents/forge/product-hub/scripts/index.js" "$DIST_SHARED/skills/forge-product/scripts/index.js" "skills/forge-product/scripts/index.js"
fi
if [ -d "$SCRIPT_DIR/agents/forge/product-hub/references" ]; then
  copy_dir "$SCRIPT_DIR/agents/forge/product-hub/references" "$DIST_SHARED/skills/forge-product/references" "skills/forge-product/references/"
fi

# Shared engineering preferences
echo "📋 Shared preferences..."
if [ -d "$SCRIPT_DIR/agents/forge/shared" ]; then
  for f in "$SCRIPT_DIR/agents/forge/shared"/*.md; do
    fname=$(basename "$f")
    copy_file "$f" "$DIST_SHARED/skills/forge-shared-prefs/references/$fname" "skills/forge-shared-prefs/references/$fname"
  done
fi

# Forge schemas (used by shared modes)
echo "🧾 Forge schemas..."
if [ -d "$SCRIPT_DIR/agents/forge/schemas" ]; then
  for f in "$SCRIPT_DIR/agents/forge/schemas"/*.md; do
    fname=$(basename "$f")
    copy_file "$f" "$DIST_SHARED/skills/forge-shared-prefs/references/schemas/$fname" "skills/forge-shared-prefs/references/schemas/$fname"
  done
fi

# Forge references (product-routing, worker-spawning)
echo "📚 Forge references..."
if [ -d "$SCRIPT_DIR/agents/forge/references" ]; then
  for f in "$SCRIPT_DIR/agents/forge/references"/*.md; do
    fname=$(basename "$f")
    copy_file "$f" "$DIST_SHARED/skills/forge-shared-prefs/references/$fname" "skills/forge-shared-prefs/references/$fname"
  done
fi

# Infrastructure skills
echo "🔧 Infrastructure skills..."
INFRA_SKILLS=("experts-council" "backlog" "agents-hub" "copilot-cli-skill")
for skill in "${INFRA_SKILLS[@]}"; do
  src_dir="$SCRIPT_DIR/skills/$skill"
  dst_dir="$DIST_SHARED/skills/$skill"
  if [ ! -d "$src_dir" ]; then
    echo "   ❌ Missing: skills/$skill/"
    TOTAL=$((TOTAL + 1))
    continue
  fi
  copy_file "$src_dir/SKILL.md" "$dst_dir/SKILL.md" "skills/$skill/SKILL.md"
  if [ -f "$src_dir/scripts/index.js" ]; then
    copy_file "$src_dir/scripts/index.js" "$dst_dir/scripts/index.js" "skills/$skill/scripts/index.js"
  fi
  if [ -d "$src_dir/references" ]; then
    copy_dir "$src_dir/references" "$dst_dir/references" "skills/$skill/references/"
  fi
done

# Architecture skills
echo "🏗️  Architecture skills..."
ARCH_SKILLS=("backend-architecture" "frontend-architecture")
for skill in "${ARCH_SKILLS[@]}"; do
  src_dir="$SCRIPT_DIR/skills/$skill"
  dst_dir="$DIST_SHARED/skills/$skill"
  if [ ! -d "$src_dir" ]; then
    echo "   ❌ Missing: skills/$skill/"
    TOTAL=$((TOTAL + 1))
    continue
  fi
  copy_file "$src_dir/SKILL.md" "$dst_dir/SKILL.md" "skills/$skill/SKILL.md"
  if [ -d "$src_dir/references" ]; then
    copy_dir "$src_dir/references" "$dst_dir/references" "skills/$skill/references/"
  fi
done

# Product management skills
echo "📋 PM skills..."
PM_SKILLS=("jobs-to-be-done" "made-to-stick" "copywriting" "lean-startup" "storybrand-messaging" "cro-methodology" "page-cro")
for skill in "${PM_SKILLS[@]}"; do
  src_dir="$SCRIPT_DIR/skills/$skill"
  dst_dir="$DIST_SHARED/skills/$skill"
  if [ ! -d "$src_dir" ]; then
    echo "   ⚠️  Optional: skills/$skill/ (skipping)"
    continue
  fi
  copy_file "$src_dir/SKILL.md" "$dst_dir/SKILL.md" "skills/$skill/SKILL.md"
  if [ -d "$src_dir/references" ]; then
    copy_dir "$src_dir/references" "$dst_dir/references" "skills/$skill/references/"
  fi
done

# ═══════════════════════════════════════════════
# PLUGIN 2: forge (Opus coordinator — 3 unique skills + agent)
# ═══════════════════════════════════════════════
echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║  2/3  forge (Opus)                            ║"
echo "╚═══════════════════════════════════════════════╝"

if ! $DRY_RUN; then rm -rf "$DIST_FORGE"; mkdir -p "$DIST_FORGE"; fi

# Manifest
echo "📦 Manifest..."
copy_file "$SCRIPT_DIR/plugin.json" "$DIST_FORGE/plugin.json" "plugin.json"

# Agent
echo "🤖 Agent..."
write_agent \
  "$SCRIPT_DIR/agents/forge/forge.agent.md" \
  "$DIST_FORGE/agents/Forge.agent.md" \
  "Your dev partner. Understands tasks, routes to the right mode, coordinates specialists, never loses the thread." \
  "claude-opus-4.6" \
  "forge.agent.md" \
  "agents/Forge.agent.md"

# Coordinator skill
echo "📜 Coordinator skill..."
copy_file "$SCRIPT_DIR/agents/forge/SKILL.md" "$DIST_FORGE/skills/forge/SKILL.md" "skills/forge/SKILL.md"

# Execute mode (Opus-specific)
echo "⚙️  Opus modes..."
copy_file "$SCRIPT_DIR/agents/forge/modes/execute.md" "$DIST_FORGE/skills/forge-execute/SKILL.md" "skills/forge-execute/SKILL.md"
copy_file "$SCRIPT_DIR/agents/forge/modes/verify.md" "$DIST_FORGE/skills/forge-verify/SKILL.md" "skills/forge-verify/SKILL.md"

# ═══════════════════════════════════════════════
# PLUGIN 3: forge-gpt (GPT coordinator — 3 unique skills + agent)
# ═══════════════════════════════════════════════
echo ""
echo "╔═══════════════════════════════════════════════╗"
echo "║  3/3  forge-gpt                               ║"
echo "╚═══════════════════════════════════════════════╝"

if ! $DRY_RUN; then rm -rf "$DIST_GPT"; mkdir -p "$DIST_GPT"; fi

# Manifest
echo "📦 Manifest..."
TOTAL=$((TOTAL + 1))
if [ -f "$SCRIPT_DIR/plugin.json" ]; then
  if $DRY_RUN; then
    echo "   Would write: plugin.json (forge-gpt)"
  else
    mkdir -p "$DIST_GPT"
    python3 -c "
import json
with open('$SCRIPT_DIR/plugin.json') as f: m = json.load(f)
m['name'] = 'forge-gpt'
m['description'] = 'Forge-GPT coordinator — GPT-optimized dispatch with contract-driven execution and verification.'
m['keywords'] = list(set(['forge-gpt','gpt-family','contract-driven'] + m.get('keywords',[])))
with open('$DIST_GPT/plugin.json', 'w') as f: json.dump(m, f, indent=2); f.write('\n')
"
    echo "   ✅ plugin.json (forge-gpt)"
  fi
  SUCCESS=$((SUCCESS + 1))
fi

# Agent
echo "🤖 Agent..."
write_agent \
  "$SCRIPT_DIR/agents/forge-gpt/forge-gpt.agent.md" \
  "$DIST_GPT/agents/Forge-GPT.agent.md" \
  "Contract-driven GPT coordinator. Routes work, constructs Mission Briefs, validates REPORTs, and stops." \
  "gpt-5.4" \
  "forge-gpt.agent.md" \
  "agents/Forge-GPT.agent.md"

# GPT coordinator skill
echo "📜 GPT coordinator skill..."
copy_file "$SCRIPT_DIR/agents/forge-gpt/SKILL.md" "$DIST_GPT/skills/forge-gpt/SKILL.md" "skills/forge-gpt/SKILL.md"

# GPT modes (execute + verify)
echo "⚙️  GPT modes..."
copy_file "$SCRIPT_DIR/agents/forge-gpt/modes/execute.md" "$DIST_GPT/skills/forge-execute-gpt/SKILL.md" "skills/forge-execute-gpt/SKILL.md"
copy_file "$SCRIPT_DIR/agents/forge-gpt/modes/verify.md" "$DIST_GPT/skills/forge-verify-gpt/SKILL.md" "skills/forge-verify-gpt/SKILL.md"

# GPT schemas
echo "🧾 GPT schemas..."
SCHEMA_TARGETS=("forge-gpt" "forge-execute-gpt" "forge-verify-gpt")
SCHEMA_FILES=("mission-brief.v1.md" "report.v1.md")
for target in "${SCHEMA_TARGETS[@]}"; do
  for schema in "${SCHEMA_FILES[@]}"; do
    copy_file \
      "$SCRIPT_DIR/agents/forge-gpt/schemas/${schema}" \
      "$DIST_GPT/skills/${target}/references/schemas/${schema}" \
      "skills/${target}/references/schemas/${schema}"
  done
done

# ═══════════════════════════════════════════════
# Cleanup
# ═══════════════════════════════════════════════
if ! $DRY_RUN; then
  find "$DIST_SHARED" "$DIST_FORGE" "$DIST_GPT" -name '.DS_Store' -delete 2>/dev/null || true
fi

# ═══════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════
echo ""
echo "═══════════════════════════════════════════════"
if $DRY_RUN; then
  echo "📊 Dry-run: would build $SUCCESS/$TOTAL components"
else
  S1=$(find "$DIST_SHARED" -type f | wc -l | tr -d ' ')
  S2=$(find "$DIST_FORGE" -type f | wc -l | tr -d ' ')
  S3=$(find "$DIST_GPT" -type f | wc -l | tr -d ' ')
  echo "✅ Built $SUCCESS/$TOTAL components"
  echo ""
  echo "  forge-shared:  $S1 files  ($(du -sh "$DIST_SHARED" | cut -f1))"
  echo "  forge:         $S2 files  ($(du -sh "$DIST_FORGE" | cut -f1))"
  echo "  forge-gpt:     $S3 files  ($(du -sh "$DIST_GPT" | cut -f1))"
fi

# ═══════════════════════════════════════════════
# Install
# ═══════════════════════════════════════════════
if $INSTALL && ! $DRY_RUN; then
  echo ""
  echo "🚀 Installing plugins..."

  copilot plugin uninstall forge-shared 2>/dev/null || true
  copilot plugin uninstall forge 2>/dev/null || true
  copilot plugin uninstall forge-gpt 2>/dev/null || true

  copilot plugin install "$DIST_SHARED"
  copilot plugin install "$DIST_FORGE"
  copilot plugin install "$DIST_GPT"

  echo ""
  copilot plugin list
fi

echo ""
echo "═══════════════════════════════════════════════"
[ "$SUCCESS" -eq "$TOTAL" ] || exit 1
