#!/usr/bin/env bash
set -euo pipefail

# Build the Forge-GPT plugin for distribution.
#
# Assembles a standalone Forge-GPT plugin bundle from source:
#   - agents/forge-gpt/forge-gpt.agent.md → dist-forge-gpt/agents/Forge-GPT.agent.md (with frontmatter)
#   - agents/forge-gpt/SKILL.md → dist-forge-gpt/skills/forge-gpt/SKILL.md
#   - agents/forge-gpt/modes/{execute,verify}.md → dist-forge-gpt/skills/forge-{mode}-gpt/SKILL.md
#   - agents/forge-gpt/schemas/*.md → dist-forge-gpt/skills/forge-*/references/schemas/
#   - agents/forge/modes/{explore,ideate,design,plan,memory}.md → dist-forge-gpt/skills/forge-{mode}/SKILL.md (shared)
#   - agents/forge/shared/* → dist-forge-gpt/skills/forge-gpt/references/shared/ (shared prefs)
#   - agents/forge/product-hub/ → dist-forge-gpt/skills/forge-product/ (bundle + refs)
#   - skills/* → dist-forge-gpt/skills/* (infrastructure + architecture + PM skills)
#   - plugin.json (rewritten as forge-gpt) → dist-forge-gpt/plugin.json
#   - .mcp.json → dist-forge-gpt/.mcp.json
#
# Usage:
#   ./build-forge-gpt-plugin.sh              # build to dist-forge-gpt/
#   ./build-forge-gpt-plugin.sh --install    # build + copilot plugin install
#   ./build-forge-gpt-plugin.sh --dry-run    # preview without writing

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DIST="$SCRIPT_DIR/dist-forge-gpt"
DRY_RUN=false
INSTALL=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --install) INSTALL=true ;;
    *) echo "Unknown: $arg"; exit 1 ;;
  esac
done

echo "🤖 Forge-GPT Plugin Builder"
echo "   Source: $SCRIPT_DIR"
echo "   Output: $DIST"
echo ""

SUCCESS=0
TOTAL=0

# --- Helpers ---
copy_file() {
  local src="$1" dst="$2" label="$3"
  TOTAL=$((TOTAL + 1))
  if [ ! -f "$src" ]; then
    echo "   ❌ Missing: $src"
    return 1
  fi
  if $DRY_RUN; then
    echo "   Would copy: $label"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "   ✅ $label"
  fi
  SUCCESS=$((SUCCESS + 1))
}

copy_dir() {
  local src="$1" dst="$2" label="$3"
  TOTAL=$((TOTAL + 1))
  if [ ! -d "$src" ]; then
    echo "   ❌ Missing dir: $src"
    return 1
  fi
  if $DRY_RUN; then
    echo "   Would copy dir: $label"
  else
    mkdir -p "$dst"
    cp -r "$src"/* "$dst"/
    echo "   ✅ $label"
  fi
  SUCCESS=$((SUCCESS + 1))
}

# --- Clean ---
if ! $DRY_RUN; then
  rm -rf "$DIST"
  mkdir -p "$DIST"
fi

# --- Step 1: Plugin manifest (rewritten for forge-gpt) ---
echo "📦 Plugin manifest..."
TOTAL=$((TOTAL + 1))
if [ -f "$SCRIPT_DIR/plugin.json" ]; then
  if $DRY_RUN; then
    echo "   Would write: plugin.json (forge-gpt manifest)"
  else
    mkdir -p "$DIST"
    python3 -c "
import json, sys
with open('$SCRIPT_DIR/plugin.json') as f: m = json.load(f)
m['name'] = 'forge-gpt'
m['description'] = 'Forge-GPT dev partner — GPT-family optimized dispatch coordinator with contract-driven execution, verification, and shared Forge exploration modes.'
kw = list(set(['forge-gpt','gpt-family','contract-driven'] + m.get('keywords',[])))
m['keywords'] = kw
with open('$DIST/plugin.json', 'w') as f: json.dump(m, f, indent=2); f.write('\n')
"
    echo "   ✅ plugin.json (forge-gpt manifest)"
  fi
  SUCCESS=$((SUCCESS + 1))
else
  echo "   ❌ Missing: plugin.json"
fi
copy_file "$SCRIPT_DIR/.mcp.json" "$DIST/.mcp.json" ".mcp.json"

# --- Step 2: Agent ---
echo ""
echo "🤖 Agent..."

AGENT_SRC="$SCRIPT_DIR/agents/forge-gpt/forge-gpt.agent.md"
AGENT_DST="$DIST/agents/Forge-GPT.agent.md"
TOTAL=$((TOTAL + 1))

if [ -f "$AGENT_SRC" ]; then
  BODY=$(awk 'NR>1 && /^[#*>\[]/{found=1} found{print}' "$AGENT_SRC")
  if [ -z "$BODY" ]; then
    BODY=$(tail -n +3 "$AGENT_SRC")
  fi

  FRONTMATTER="---
description: 'Contract-driven GPT coordinator. Routes work, constructs Mission Briefs, validates REPORTs, and stops.'
model: gpt-5.4
tools: [\"*\"]
---"

  RENDERED="${FRONTMATTER}

<!-- AUTO-GENERATED by build-forge-gpt-plugin.sh from forge-gpt.agent.md. DO NOT EDIT. -->

${BODY}
"

  if $DRY_RUN; then
    echo "   Would write: agents/Forge-GPT.agent.md (${#RENDERED} chars)"
  else
    mkdir -p "$DIST/agents"
    printf '%s' "$RENDERED" > "$AGENT_DST"
    echo "   ✅ agents/Forge-GPT.agent.md (${#RENDERED} chars)"
  fi
  SUCCESS=$((SUCCESS + 1))
else
  echo "   ❌ Missing: $AGENT_SRC"
fi

# --- Step 3: GPT coordinator skill ---
echo ""
echo "📜 GPT coordinator skill..."
copy_file \
  "$SCRIPT_DIR/agents/forge-gpt/SKILL.md" \
  "$DIST/skills/forge-gpt/SKILL.md" \
  "skills/forge-gpt/SKILL.md"

# --- Step 4: GPT mode skills (all from forge-gpt) ---
echo ""
echo "⚙️  GPT mode skills..."
GPT_MODES=("execute" "verify" "explore" "ideate" "design" "plan" "memory" "product")
for mode in "${GPT_MODES[@]}"; do
  copy_file \
    "$SCRIPT_DIR/agents/forge-gpt/modes/${mode}.md" \
    "$DIST/skills/forge-${mode}-gpt/SKILL.md" \
    "skills/forge-${mode}-gpt/SKILL.md"
done

# --- Step 5: Product-hub tooling (shared infrastructure) ---
echo ""
echo "📦 Product-hub tooling..."

if [ -f "$SCRIPT_DIR/agents/forge/product-hub/scripts/index.js" ]; then
  copy_file \
    "$SCRIPT_DIR/agents/forge/product-hub/scripts/index.js" \
    "$DIST/skills/forge-product-gpt/scripts/index.js" \
    "skills/forge-product-gpt/scripts/index.js"
else
  echo "   ⚠️  Product-hub not built. Run: cd agents/forge/product-hub && npm run build"
fi
if [ -d "$SCRIPT_DIR/agents/forge/product-hub/references" ]; then
  copy_dir \
    "$SCRIPT_DIR/agents/forge/product-hub/references" \
    "$DIST/skills/forge-product-gpt/references" \
    "skills/forge-product-gpt/references/"
fi

# --- Step 6: Shared engineering preferences ---
echo ""
echo "📋 Shared preferences..."
if [ -d "$SCRIPT_DIR/agents/forge/shared" ]; then
  for f in "$SCRIPT_DIR/agents/forge/shared"/*.md; do
    fname=$(basename "$f")
    copy_file "$f" "$DIST/skills/forge-gpt/references/shared/$fname" "skills/forge-gpt/references/shared/$fname"
  done
fi

# --- Step 7: Forge references ---
echo ""
echo "📚 Forge references..."
if [ -d "$SCRIPT_DIR/agents/forge/references" ]; then
  for f in "$SCRIPT_DIR/agents/forge/references"/*.md; do
    fname=$(basename "$f")
    copy_file "$f" "$DIST/skills/forge-gpt/references/$fname" "skills/forge-gpt/references/$fname"
  done
fi

# --- Step 8: Visual vocabulary spec ---
echo ""
echo "📐 Visual vocabulary..."
copy_file \
  "$SCRIPT_DIR/agents/forge/docs/specs/visual-vocabulary.md" \
  "$DIST/skills/forge-gpt/references/specs/visual-vocabulary.md" \
  "skills/forge-gpt/references/specs/visual-vocabulary.md"

# --- Step 8b: External voice spec ---
echo "🗣️  External voice..."
copy_file \
  "$SCRIPT_DIR/agents/forge/docs/specs/external-voice.md" \
  "$DIST/skills/forge-gpt/references/specs/external-voice.md" \
  "skills/forge-gpt/references/specs/external-voice.md"

# --- Step 8c: Design artifacts spec ---
echo "🎨 Design artifacts..."
copy_file \
  "$SCRIPT_DIR/agents/forge/docs/specs/design-artifacts.md" \
  "$DIST/skills/forge-gpt/references/specs/design-artifacts.md" \
  "skills/forge-gpt/references/specs/design-artifacts.md"

# --- Step 8d: Design review template ---
echo "📄 Design review template..."
copy_file \
  "$SCRIPT_DIR/agents/forge/templates/design-review.html" \
  "$DIST/skills/forge-gpt/references/templates/design-review.html" \
  "skills/forge-gpt/references/templates/design-review.html"

# --- Step 10: Infrastructure skills ---
echo ""
echo "🔧 Infrastructure skills..."
INFRA_SKILLS=("experts-council" "backlog" "agents-hub" "copilot-cli-skill")
for skill in "${INFRA_SKILLS[@]}"; do
  src_dir="$SCRIPT_DIR/skills/$skill"
  dst_dir="$DIST/skills/$skill"
  if [ ! -d "$src_dir" ]; then
    echo "   ❌ Missing: skills/$skill/"
    TOTAL=$((TOTAL + 1))
    continue
  fi
  copy_file "$src_dir/SKILL.md" "$dst_dir/SKILL.md" "skills/$skill/SKILL.md"
  if [ -f "$src_dir/scripts/index.js" ]; then
    copy_file "$src_dir/scripts/index.js" "$dst_dir/scripts/index.js" "skills/$skill/scripts/index.js"
  fi
  if [ -d "$src_dir/references" ]; then
    copy_dir "$src_dir/references" "$dst_dir/references" "skills/$skill/references/"
  fi
done

# --- Step 11: Architecture skills ---
echo ""
echo "🏗️  Architecture skills..."
ARCH_SKILLS=("backend-architecture" "frontend-architecture")
for skill in "${ARCH_SKILLS[@]}"; do
  src_dir="$SCRIPT_DIR/skills/$skill"
  dst_dir="$DIST/skills/$skill"
  if [ ! -d "$src_dir" ]; then
    echo "   ❌ Missing: skills/$skill/"
    TOTAL=$((TOTAL + 1))
    continue
  fi
  copy_file "$src_dir/SKILL.md" "$dst_dir/SKILL.md" "skills/$skill/SKILL.md"
  if [ -d "$src_dir/references" ]; then
    copy_dir "$src_dir/references" "$dst_dir/references" "skills/$skill/references/"
  fi
done

# --- Step 12: Product management skills ---
echo ""
echo "📋 Product management skills..."
PM_SKILLS=("jobs-to-be-done" "made-to-stick" "copywriting" "lean-startup" "storybrand-messaging" "cro-methodology" "page-cro")
for skill in "${PM_SKILLS[@]}"; do
  src_dir="$SCRIPT_DIR/skills/$skill"
  dst_dir="$DIST/skills/$skill"
  if [ ! -d "$src_dir" ]; then
    echo "   ⚠️  Optional: skills/$skill/ not found (skipping)"
    continue
  fi
  copy_file "$src_dir/SKILL.md" "$dst_dir/SKILL.md" "skills/$skill/SKILL.md"
  if [ -d "$src_dir/references" ]; then
    copy_dir "$src_dir/references" "$dst_dir/references" "skills/$skill/references/"
  fi
done

# --- Cleanup artifacts ---
if ! $DRY_RUN; then
  find "$DIST" -name '.DS_Store' -delete 2>/dev/null || true
fi

# --- Summary ---
echo ""
echo "═══════════════════════════════════════════════"
if $DRY_RUN; then
  echo "📊 Dry-run: would build $SUCCESS/$TOTAL components"
else
  echo "✅ Built $SUCCESS/$TOTAL components → $DIST/"
  echo ""
  echo "Plugin structure:"
  find "$DIST" -type f | sed "s|$DIST/|  |" | sort | head -50
  TOTAL_SIZE=$(du -sh "$DIST" | cut -f1)
  echo ""
  echo "Total size: $TOTAL_SIZE"
fi

# --- Install ---
if $INSTALL && ! $DRY_RUN; then
  echo ""
  echo "🚀 Installing plugin..."
  copilot plugin uninstall forge-gpt 2>/dev/null || true
  copilot plugin install "$DIST"
  echo ""
  copilot plugin list
fi

echo ""
echo "═══════════════════════════════════════════════"
[ "$SUCCESS" -eq "$TOTAL" ] || exit 1
