# Build the Forge plugin for distribution.
#
# Assembles the plugin structure from source:
#   - agents/forge/forge.agent.md -> dist/agents/Forge.agent.md (with frontmatter)
#   - agents/forge/SKILL.md -> dist/skills/forge/SKILL.md
#   - agents/forge/modes/*.md -> dist/skills/forge-{mode}/SKILL.md
#   - agents/forge/product-hub/ -> dist/skills/forge-product/ (bundle + refs)
#   - skills/* -> dist/skills/* (infrastructure skills)
#   - plugin.json -> dist/plugin.json
#   - .mcp.json -> dist/.mcp.json
#
# Usage:
#   .\build-plugin.ps1              # build to dist/
#   .\build-plugin.ps1 -Install     # build + copilot plugin install
#   .\build-plugin.ps1 -DryRun      # preview without writing

param(
    [switch]$DryRun,
    [switch]$Install
)

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$Dist      = Join-Path $ScriptDir 'dist'

Write-Host "🔨 Forge Plugin Builder"
Write-Host "   Source: $ScriptDir"
Write-Host "   Output: $Dist"
Write-Host ""

$script:Success = 0
$script:Total   = 0

# --- Helpers ---
function Copy-PluginFile {
    param([string]$Src, [string]$Dst, [string]$Label)
    $script:Total++
    if (-not (Test-Path $Src -PathType Leaf)) {
        Write-Host "   ❌ Missing: $Src"
        return $false
    }
    if ($DryRun) {
        Write-Host "   Would copy: $Label"
    } else {
        $parent = Split-Path -Parent $Dst
        if (-not (Test-Path $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
        Copy-Item -Path $Src -Destination $Dst -Force
        Write-Host "   ✅ $Label"
    }
    $script:Success++
    return $true
}

function Copy-PluginDir {
    param([string]$Src, [string]$Dst, [string]$Label)
    $script:Total++
    if (-not (Test-Path $Src -PathType Container)) {
        Write-Host "   ❌ Missing dir: $Src"
        return $false
    }
    if ($DryRun) {
        Write-Host "   Would copy dir: $Label"
    } else {
        if (-not (Test-Path $Dst)) { New-Item -ItemType Directory -Path $Dst -Force | Out-Null }
        Copy-Item -Path "$Src\*" -Destination $Dst -Recurse -Force
        Write-Host "   ✅ $Label"
    }
    $script:Success++
    return $true
}

# --- Clean ---
if (-not $DryRun) {
    if (Test-Path $Dist) { Remove-Item -Recurse -Force $Dist }
    New-Item -ItemType Directory -Path $Dist -Force | Out-Null
}

# --- Step 1: Plugin manifest ---
Write-Host "📦 Plugin manifest..."
Copy-PluginFile "$ScriptDir\plugin.json" "$Dist\plugin.json" "plugin.json" | Out-Null
Copy-PluginFile "$ScriptDir\.mcp.json" "$Dist\.mcp.json" ".mcp.json" | Out-Null

# --- Step 2: Agent ---
Write-Host ""
Write-Host "🤖 Agent..."

$AgentSrc = "$ScriptDir\agents\forge\forge.agent.md"
$AgentDst = "$Dist\agents\Forge.agent.md"
$script:Total++

if (Test-Path $AgentSrc -PathType Leaf) {
    $lines = Get-Content $AgentSrc -Raw
    # Extract body — skip H1 title, keep everything from first content line
    $allLines = $lines -split "`n"
    $body = $null
    $found = $false
    $bodyLines = @()
    for ($i = 1; $i -lt $allLines.Count; $i++) {
        if (-not $found -and $allLines[$i] -match '^[#*>\[]') { $found = $true }
        if ($found) { $bodyLines += $allLines[$i] }
    }
    if ($bodyLines.Count -gt 0) {
        $body = $bodyLines -join "`n"
    } else {
        $body = ($allLines | Select-Object -Skip 2) -join "`n"
    }

    $frontmatter = @"
---
description: 'Your dev partner. Understands tasks, routes to the right mode, coordinates specialists, never loses the thread.'
model: claude-opus-4.6
tools: ["*"]
---
"@

    $rendered = "$frontmatter`n`n<!-- AUTO-GENERATED by build-plugin.ps1 from forge.agent.md. DO NOT EDIT. -->`n`n$body`n"

    if ($DryRun) {
        Write-Host "   Would write: agents/Forge.agent.md ($($rendered.Length) chars)"
    } else {
        $agentDir = Split-Path -Parent $AgentDst
        if (-not (Test-Path $agentDir)) { New-Item -ItemType Directory -Path $agentDir -Force | Out-Null }
        [System.IO.File]::WriteAllText($AgentDst, $rendered)
        Write-Host "   ✅ agents/Forge.agent.md ($($rendered.Length) chars)"
    }
    $script:Success++
} else {
    Write-Host "   ❌ Missing: $AgentSrc"
}

# --- Step 3: Coordinator skill ---
Write-Host ""
Write-Host "📜 Coordinator skill..."
Copy-PluginFile `
    "$ScriptDir\agents\forge\SKILL.md" `
    "$Dist\skills\forge\SKILL.md" `
    "skills/forge/SKILL.md" | Out-Null

# --- Step 4: Mode skills ---
Write-Host ""
Write-Host "⚙️  Mode skills..."
$modes = @("explore", "ideate", "design", "plan", "execute", "verify", "memory", "product")
foreach ($mode in $modes) {
    Copy-PluginFile `
        "$ScriptDir\agents\forge\modes\$mode.md" `
        "$Dist\skills\forge-$mode\SKILL.md" `
        "skills/forge-$mode/SKILL.md" | Out-Null
}

# --- Step 5: Product-hub library ---
Write-Host ""
Write-Host "📦 Product-hub..."
$phIndex = "$ScriptDir\agents\forge\product-hub\scripts\index.js"
if (Test-Path $phIndex -PathType Leaf) {
    Copy-PluginFile `
        $phIndex `
        "$Dist\skills\forge-product\scripts\index.js" `
        "skills/forge-product/scripts/index.js" | Out-Null
} else {
    Write-Host "   ⚠️  Not built. Run: cd agents\forge\product-hub; npm run build"
}
$phRefs = "$ScriptDir\agents\forge\product-hub\references"
if (Test-Path $phRefs -PathType Container) {
    Copy-PluginDir `
        $phRefs `
        "$Dist\skills\forge-product\references" `
        "skills/forge-product/references/" | Out-Null
}

# --- Step 5b: Shared preferences ---
Write-Host ""
Write-Host "📋 Shared preferences..."
$sharedDir = "$ScriptDir\agents\forge\shared"
if (Test-Path $sharedDir -PathType Container) {
    Get-ChildItem -Path $sharedDir -Filter '*.md' | ForEach-Object {
        Copy-PluginFile $_.FullName "$Dist\skills\forge\references\shared\$($_.Name)" "skills/forge/references/shared/$($_.Name)" | Out-Null
    }
}

# --- Step 5c: Forge schemas ---
Write-Host ""
Write-Host "🧾 Forge schemas..."
$schemasDir = "$ScriptDir\agents\forge\schemas"
if (Test-Path $schemasDir -PathType Container) {
    Get-ChildItem -Path $schemasDir -Filter '*.md' | ForEach-Object {
        Copy-PluginFile $_.FullName "$Dist\skills\forge\references\schemas\$($_.Name)" "skills/forge/references/schemas/$($_.Name)" | Out-Null
    }
}

# --- Step 5d: Forge references ---
Write-Host ""
Write-Host "📚 Forge references..."
$forgeRefsDir = "$ScriptDir\agents\forge\references"
if (Test-Path $forgeRefsDir -PathType Container) {
    Get-ChildItem -Path $forgeRefsDir -Filter '*.md' | ForEach-Object {
        Copy-PluginFile $_.FullName "$Dist\skills\forge\references\$($_.Name)" "skills/forge/references/$($_.Name)" | Out-Null
    }
}

# --- Step 5e: Visual vocabulary spec ---
Write-Host ""
Write-Host "📐 Visual vocabulary..."
Copy-PluginFile `
    "$ScriptDir\agents\forge\docs\specs\visual-vocabulary.md" `
    "$Dist\skills\forge\references\specs\visual-vocabulary.md" `
    "skills/forge/references/specs/visual-vocabulary.md" | Out-Null

# --- Step 5f: External voice spec ---
Write-Host "🗣️  External voice..."
Copy-PluginFile `
    "$ScriptDir\agents\forge\docs\specs\external-voice.md" `
    "$Dist\skills\forge\references\specs\external-voice.md" `
    "skills/forge/references/specs/external-voice.md" | Out-Null

# --- Step 5g: Design artifacts spec ---
Write-Host "🎨 Design artifacts..."
Copy-PluginFile `
    "$ScriptDir\agents\forge\docs\specs\design-artifacts.md" `
    "$Dist\skills\forge\references\specs\design-artifacts.md" `
    "skills/forge/references/specs/design-artifacts.md" | Out-Null

# --- Step 5h: Design review template ---
Write-Host "📄 Design review template..."
Copy-PluginFile `
    "$ScriptDir\agents\forge\templates\design-review.html" `
    "$Dist\skills\forge\references\templates\design-review.html" `
    "skills/forge/references/templates/design-review.html" | Out-Null

# --- Step 6: Infrastructure skills ---
Write-Host ""
Write-Host "🔧 Infrastructure skills..."
$infraSkills = @("experts-council", "backlog", "agents-hub", "copilot-cli-skill")
foreach ($skill in $infraSkills) {
    $srcDir = "$ScriptDir\skills\$skill"
    $dstDir = "$Dist\skills\$skill"
    if (-not (Test-Path $srcDir -PathType Container)) {
        Write-Host "   ❌ Missing: skills/$skill/"
        $script:Total++
        continue
    }
    Copy-PluginFile "$srcDir\SKILL.md" "$dstDir\SKILL.md" "skills/$skill/SKILL.md" | Out-Null
    $scriptIndex = "$srcDir\scripts\index.js"
    if (Test-Path $scriptIndex -PathType Leaf) {
        Copy-PluginFile $scriptIndex "$dstDir\scripts\index.js" "skills/$skill/scripts/index.js" | Out-Null
    }
    $refsDir = "$srcDir\references"
    if (Test-Path $refsDir -PathType Container) {
        Copy-PluginDir $refsDir "$dstDir\references" "skills/$skill/references/" | Out-Null
    }
}

# --- Step 7: Architecture skills ---
Write-Host ""
Write-Host "🏗️  Architecture skills..."
$archSkills = @("backend-architecture", "frontend-architecture")
foreach ($skill in $archSkills) {
    $srcDir = "$ScriptDir\skills\$skill"
    $dstDir = "$Dist\skills\$skill"
    if (-not (Test-Path $srcDir -PathType Container)) {
        Write-Host "   ❌ Missing: skills/$skill/"
        $script:Total++
        continue
    }
    Copy-PluginFile "$srcDir\SKILL.md" "$dstDir\SKILL.md" "skills/$skill/SKILL.md" | Out-Null
    $refsDir = "$srcDir\references"
    if (Test-Path $refsDir -PathType Container) {
        Copy-PluginDir $refsDir "$dstDir\references" "skills/$skill/references/" | Out-Null
    }
}

# --- Step 8: Product management skills ---
Write-Host ""
Write-Host "📋 Product management skills..."
$pmSkills = @("jobs-to-be-done", "made-to-stick", "copywriting", "lean-startup", "storybrand-messaging", "cro-methodology", "page-cro")
foreach ($skill in $pmSkills) {
    $srcDir = "$ScriptDir\skills\$skill"
    $dstDir = "$Dist\skills\$skill"
    if (-not (Test-Path $srcDir -PathType Container)) {
        Write-Host "   ⚠️  Optional: skills/$skill/ not found (skipping)"
        continue
    }
    Copy-PluginFile "$srcDir\SKILL.md" "$dstDir\SKILL.md" "skills/$skill/SKILL.md" | Out-Null
    $refsDir = "$srcDir\references"
    if (Test-Path $refsDir -PathType Container) {
        Copy-PluginDir $refsDir "$dstDir\references" "skills/$skill/references/" | Out-Null
    }
}

# --- Cleanup artifacts ---
if (-not $DryRun) {
    Get-ChildItem -Path $Dist -Recurse -Filter '.DS_Store' -ErrorAction SilentlyContinue |
        Remove-Item -Force -ErrorAction SilentlyContinue
}

# --- Summary ---
Write-Host ""
Write-Host "═══════════════════════════════════════════════"
if ($DryRun) {
    Write-Host "📊 Dry-run: would build $($script:Success)/$($script:Total) components"
} else {
    Write-Host "✅ Built $($script:Success)/$($script:Total) components → $Dist\"
    Write-Host ""
    Write-Host "Plugin structure:"
    Get-ChildItem -Path $Dist -Recurse -File |
        ForEach-Object { $_.FullName.Replace("$Dist\", "  ") } |
        Sort-Object |
        Select-Object -First 40 |
        ForEach-Object { Write-Host $_ }
    $totalSize = "{0:N2} MB" -f ((Get-ChildItem -Path $Dist -Recurse -File | Measure-Object -Property Length -Sum).Sum / 1MB)
    Write-Host ""
    Write-Host "Total size: $totalSize"
}

# --- Install ---
if ($Install -and -not $DryRun) {
    Write-Host ""
    Write-Host "🚀 Installing plugin..."
    try { copilot plugin uninstall forge 2>$null } catch {}
    copilot plugin install $Dist
    Write-Host ""
    copilot plugin list
}

Write-Host ""
Write-Host "═══════════════════════════════════════════════"
if ($script:Success -ne $script:Total) { exit 1 }
