#!/usr/bin/env bash
set -euo pipefail

# Build the Forge plugin for distribution.
#
# Assembles the plugin structure from source:
#   - agents/forge/forge.agent.md → dist/agents/Forge.agent.md (with frontmatter)
#   - agents/forge/SKILL.md → dist/skills/forge/SKILL.md
#   - agents/forge/modes/*.md → dist/skills/forge-{mode}/SKILL.md
#   - agents/forge/product-hub/ → dist/skills/forge-product/ (bundle + refs)
#   - skills/* → dist/skills/* (infrastructure skills)
#   - plugin.json → dist/plugin.json
#
# Usage:
#   ./build-plugin.sh              # build to dist/
#   ./build-plugin.sh --install    # build + copilot plugin install
#   ./build-plugin.sh --dry-run    # preview without writing

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DIST="$SCRIPT_DIR/dist"
DRY_RUN=false
INSTALL=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --install) INSTALL=true ;;
    *) echo "Unknown: $arg"; exit 1 ;;
  esac
done

echo "🔨 Forge Plugin Builder"
echo "   Source: $SCRIPT_DIR"
echo "   Output: $DIST"
echo ""

SUCCESS=0
TOTAL=0

# --- Helper ---
copy_file() {
  local src="$1" dst="$2" label="$3"
  TOTAL=$((TOTAL + 1))
  if [ ! -f "$src" ]; then
    echo "   ❌ Missing: $src"
    return 1
  fi
  if $DRY_RUN; then
    echo "   Would copy: $label"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "   ✅ $label"
  fi
  SUCCESS=$((SUCCESS + 1))
}

copy_dir() {
  local src="$1" dst="$2" label="$3"
  TOTAL=$((TOTAL + 1))
  if [ ! -d "$src" ]; then
    echo "   ❌ Missing dir: $src"
    return 1
  fi
  if $DRY_RUN; then
    echo "   Would copy dir: $label"
  else
    mkdir -p "$dst"
    cp -r "$src"/* "$dst"/ 2>/dev/null || true
    echo "   ✅ $label"
  fi
  SUCCESS=$((SUCCESS + 1))
}

# --- Clean ---
if ! $DRY_RUN; then
  rm -rf "$DIST"
  mkdir -p "$DIST"
fi

# --- Step 1: Plugin manifest ---
echo "📦 Plugin manifest..."
copy_file "$SCRIPT_DIR/plugin.json" "$DIST/plugin.json" "plugin.json"

# --- Step 2: Agent ---
echo ""
echo "🤖 Agent..."

AGENT_SRC="$SCRIPT_DIR/agents/forge/forge.agent.md"
AGENT_DST="$DIST/agents/Forge.agent.md"
TOTAL=$((TOTAL + 1))

if [ -f "$AGENT_SRC" ]; then
  # Extract body — skip H1 title, keep everything from first content line
  BODY=$(awk 'NR>1 && /^[#*>\[]/{found=1} found{print}' "$AGENT_SRC")
  if [ -z "$BODY" ]; then
    BODY=$(tail -n +3 "$AGENT_SRC")
  fi

  FRONTMATTER="---
description: 'Your dev partner. Understands tasks, routes to the right mode, coordinates specialists, never loses the thread.'
model: claude-opus-4.6
tools: [\"*\"]
---"

  RENDERED="${FRONTMATTER}

<!-- AUTO-GENERATED by build-plugin.sh from forge.agent.md. DO NOT EDIT. -->

${BODY}
"

  if $DRY_RUN; then
    echo "   Would write: agents/Forge.agent.md (${#RENDERED} chars)"
  else
    mkdir -p "$DIST/agents"
    printf '%s' "$RENDERED" > "$AGENT_DST"
    echo "   ✅ agents/Forge.agent.md (${#RENDERED} chars)"
  fi
  SUCCESS=$((SUCCESS + 1))
else
  echo "   ❌ Missing: $AGENT_SRC"
fi

# --- Step 3: Coordinator skill ---
echo ""
echo "📜 Coordinator skill..."
copy_file \
  "$SCRIPT_DIR/agents/forge/SKILL.md" \
  "$DIST/skills/forge/SKILL.md" \
  "skills/forge/SKILL.md"

# --- Step 4: Mode skills ---
echo ""
echo "⚙️  Mode skills..."
MODES=("explore" "ideate" "plan" "execute" "verify" "memory" "product")
for mode in "${MODES[@]}"; do
  copy_file \
    "$SCRIPT_DIR/agents/forge/modes/${mode}.md" \
    "$DIST/skills/forge-${mode}/SKILL.md" \
    "skills/forge-${mode}/SKILL.md"
done

# --- Step 5: Product-hub library ---
echo ""
echo "📦 Product-hub..."
if [ -f "$SCRIPT_DIR/agents/forge/product-hub/scripts/index.js" ]; then
  copy_file \
    "$SCRIPT_DIR/agents/forge/product-hub/scripts/index.js" \
    "$DIST/skills/forge-product/scripts/index.js" \
    "skills/forge-product/scripts/index.js"
else
  echo "   ⚠️  Not built. Run: cd agents/forge/product-hub && npm run build"
fi
if [ -d "$SCRIPT_DIR/agents/forge/product-hub/references" ]; then
  copy_dir \
    "$SCRIPT_DIR/agents/forge/product-hub/references" \
    "$DIST/skills/forge-product/references" \
    "skills/forge-product/references/"
fi

# --- Step 6: Infrastructure skills ---
echo ""
echo "🔧 Infrastructure skills..."
INFRA_SKILLS=("experts-council" "backlog" "agents-hub" "copilot-cli-skill")
for skill in "${INFRA_SKILLS[@]}"; do
  src_dir="$SCRIPT_DIR/skills/$skill"
  dst_dir="$DIST/skills/$skill"
  if [ ! -d "$src_dir" ]; then
    echo "   ❌ Missing: skills/$skill/"
    TOTAL=$((TOTAL + 1))
    continue
  fi

  # SKILL.md
  copy_file "$src_dir/SKILL.md" "$dst_dir/SKILL.md" "skills/$skill/SKILL.md"

  # scripts/ (ncc bundles)
  if [ -f "$src_dir/scripts/index.js" ]; then
    copy_file "$src_dir/scripts/index.js" "$dst_dir/scripts/index.js" "skills/$skill/scripts/index.js"
  fi

  # references/
  if [ -d "$src_dir/references" ]; then
    copy_dir "$src_dir/references" "$dst_dir/references" "skills/$skill/references/"
  fi
done

# --- Step 7: Architecture skills ---
echo ""
echo "🏗️  Architecture skills..."
ARCH_SKILLS=("backend-architecture" "frontend-architecture")
for skill in "${ARCH_SKILLS[@]}"; do
  src_dir="$SCRIPT_DIR/skills/$skill"
  dst_dir="$DIST/skills/$skill"
  if [ ! -d "$src_dir" ]; then
    echo "   ❌ Missing: skills/$skill/"
    TOTAL=$((TOTAL + 1))
    continue
  fi

  copy_file "$src_dir/SKILL.md" "$dst_dir/SKILL.md" "skills/$skill/SKILL.md"

  if [ -d "$src_dir/references" ]; then
    copy_dir "$src_dir/references" "$dst_dir/references" "skills/$skill/references/"
  fi
done

# --- Summary ---
echo ""
echo "═══════════════════════════════════════════════"
if $DRY_RUN; then
  echo "📊 Dry-run: would build $SUCCESS/$TOTAL components"
else
  echo "✅ Built $SUCCESS/$TOTAL components → $DIST/"
  echo ""
  echo "Plugin structure:"
  find "$DIST" -type f | sed "s|$DIST/|  |" | sort | head -40
  TOTAL_SIZE=$(du -sh "$DIST" | cut -f1)
  echo ""
  echo "Total size: $TOTAL_SIZE"
fi

# --- Install ---
if $INSTALL && ! $DRY_RUN; then
  echo ""
  echo "🚀 Installing plugin..."

  # Uninstall existing if present
  copilot plugin uninstall forge 2>/dev/null || true

  # Install from local dist/
  copilot plugin install "$DIST"
  echo ""
  copilot plugin list
fi

echo ""
echo "═══════════════════════════════════════════════"
[ "$SUCCESS" -eq "$TOTAL" ] || exit 1
