#!/usr/bin/env bash
set -euo pipefail

# Publish DevPartner agents and constitution skill.
#
# What it does:
#   1. Publishes SKILL.md → ~/.copilot/skills/devpartner/SKILL.md
#   2. Adds frontmatter to agents → ~/.copilot/agents/*.agent.md
#
# Usage:
#   ./publish.sh                    # publish agents + skill
#   ./publish.sh --dry-run          # preview without writing

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

VERSION_DIR="$SCRIPT_DIR"

if [ ! -f "$VERSION_DIR/SKILL.md" ]; then
  echo "❌ Cannot find SKILL.md in $VERSION_DIR"
  exit 1
fi

SKILL_TARGET="$HOME/.copilot/skills/devpartner"
AGENTS_TARGET="$HOME/.copilot/agents"

echo "🔨 DevPartner Publisher"
echo "   Source: $VERSION_DIR"
echo "   Skill target: $SKILL_TARGET"
echo "   Agents target: $AGENTS_TARGET"
echo ""

# --- Agent frontmatter definitions ---
# Format: canonical_file|output_name|description|model
AGENTS=(
  "super_orchestrator.agent.md|Super-Orchestrator.agent.md|Coordinates parallel Orchestrator sessions. Spawns workers via copilot-cli-skill, monitors progress via hub, resolves blockers, handles merges.|claude-opus-4.6"
  "orchestrator.agent.md|Orchestrator.agent.md|Central coordinator. Owns workflow, gates, user messaging. Delegates to specialists via subagents.|claude-opus-4.6"
  "scout.agent.md|Scout.agent.md|Exploration specialist. Primary file reader. Caches reads as snippets. Evidence-backed facts only. External search for post-cutoff information.|claude-sonnet-4.6"
  "creative.agent.md|Creative.agent.md|Ideation specialist. Generates differentiated approaches with tradeoffs from existing facts/snippets. No direct exploration.|claude-opus-4.6"
  "planner.agent.md|Planner.agent.md|Planning specialist. Converts approved approaches into atomic execution plans with dependencies and DONE WHEN criteria.|claude-sonnet-4.6"
  "verifier.agent.md|Verifier.agent.md|Independent critic. Validates plans/results with strict pass limits and evidence-based checks.|claude-opus-4.6"
  "executor.agent.md|Executor.agent.md|Implementation specialist. Interleaved execution with incremental verification. Only role that edits source files.|gpt-5.3-codex"
  "memory_miner.agent.md|Memory-Miner.agent.md|Memory extraction specialist. Runs only on explicit user request. Extracts durable memories from trails.|claude-opus-4.6"
)

# --- Step 1: Publish constitution skill ---
echo "📜 Publishing devpartner skill..."

# Prefer SKILL.md, fall back to _constitution.md for legacy versions
if [ -f "$VERSION_DIR/SKILL.md" ]; then
  CONSTITUTION="$VERSION_DIR/SKILL.md"
elif [ -f "$VERSION_DIR/_constitution.md" ]; then
  CONSTITUTION="$VERSION_DIR/_constitution.md"
else
  echo "❌ Skill file not found in $VERSION_DIR"
  exit 1
fi

CONST_CHARS=$(wc -c < "$CONSTITUTION" | tr -d ' ')

if $DRY_RUN; then
  echo "   Would write: $SKILL_TARGET/SKILL.md ($CONST_CHARS chars)"
else
  mkdir -p "$SKILL_TARGET"
  cp "$CONSTITUTION" "$SKILL_TARGET/SKILL.md"
  echo "   ✅ $SKILL_TARGET/SKILL.md ($CONST_CHARS chars)"
fi

# --- Step 2: Build and publish agent files ---
echo ""
echo "🤖 Publishing agent files..."

SUCCESS=0
TOTAL=${#AGENTS[@]}

for entry in "${AGENTS[@]}"; do
  IFS='|' read -r canonical output_name description model <<< "$entry"

  SOURCE="$VERSION_DIR/$canonical"
  if [ ! -f "$SOURCE" ]; then
    echo "   ⚠️  Skipping missing: $SOURCE"
    continue
  fi

  # Extract body from ## Role onwards
  BODY=$(sed -n '/^## Role$/,$p' "$SOURCE")
  if [ -z "$BODY" ]; then
    echo "   ❌ No '## Role' section found in $canonical"
    continue
  fi

  # Build frontmatter
  FRONTMATTER="---
description: '${description}'
model: ${model}
tools: [\"*\"]
---"

  # Assemble final content
  RENDERED="${FRONTMATTER}

<!-- AUTO-GENERATED by publish.sh from ${canonical}. DO NOT EDIT. -->

${BODY}
"

  RENDERED_CHARS=${#RENDERED}
  GLOBAL_PATH="$AGENTS_TARGET/$output_name"

  if $DRY_RUN; then
    echo "   Would write: $GLOBAL_PATH ($RENDERED_CHARS chars)"
  else
    mkdir -p "$AGENTS_TARGET"
    printf '%s' "$RENDERED" > "$GLOBAL_PATH"
    echo "   ✅ $output_name ($RENDERED_CHARS chars)"
  fi

  SUCCESS=$((SUCCESS + 1))
done

# --- Summary ---
echo ""
echo "═══════════════════════════════════════════════"
if $DRY_RUN; then
  echo "📊 Dry-run: would publish $SUCCESS/$TOTAL agents + 1 skill"
else
  echo "✅ Published $SUCCESS/$TOTAL agents + 1 skill"
  echo "   Skill: $SKILL_TARGET/SKILL.md"
  echo "   Agents: $AGENTS_TARGET/"
fi

[ "$SUCCESS" -eq "$TOTAL" ] || exit 1
